version: "3.1"

services:
  postgre:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=jelly
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./postgre_data:/var/lib/postgresql/data
